name: Process Content Issues

on:
  issues:
    types: [opened, labeled]

jobs:
  process-content:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'automation')
    steps:
      - uses: actions/checkout@v4
      
      - name: Save content to file
        run: |
          echo "${{ github.event.issue.body }}" >> data.txt
          
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Add content from issue #${{ github.event.issue.number }}'
          file_pattern: 'data.txt'
          
      - name: Close issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: 'Content saved successfully'
    
